# Generated by Django 4.2.8 on 2024-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('email', models.TextField(default='', verbose_name='Описание')),
                ('accounts', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
    ]
